name: Build WebView Overlay

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Grant execute permission
      run: chmod +x "build.sh"
    - name: Install dependencies
      run: sudo apt install git xmlstarlet aapt apktool -y
    - name: Build overlay
      run: bash build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Overlay
        path: build/treble-overlay-webview.apk
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0